### PR TITLE
FIX: buildDir Path was wrong when no workspace was opened

### LINKED ISSUE #6: Error switching to project folder
When I run a script, PowerShell issues the following error:

PS D:\> cd ":\Projects\Programming\Red"
cd : Cannot find path 'D:\:\Projects\Programming\Red' because it does not exist.
At line:1 char:1
cd ":\Projects\Programming\Red"

This happens even when I manually switch to the 'D' drive in the internal PowerShell.

### PR DESCRIPTION
**Pull request by ghost**
Closes #6

### CODE REVIEW

**Comment by nc-x** [comment]
@qtxie Although this fixes the issue, but still, is there a reason to `cd` into the directory while `interpreting`? Because the code currently -
  
First, `cd`'s into the directory.
Then, passes the whole filename with path to the console.
  
So why the need for cd?

**Comment by qtxie** [comment]
Thank you very much for fixing it. :+1:

**Comment by ghost** [comment]
You are welcome 😉

**Comment by geekyi** [comment]
The logic seems a bit complex. I think it can be simplified further.
@nc-x if you can figure it out?

**Review by geekyi — CHANGES_REQUESTED** [review]
https://github.com/red/VScode-extension/pull/9/files#diff-4c8cd72104a9d2b98692bec591fc520eR114
> `buildDir = redSettings.buildDir`

This is the only code that's different in the path logic, so:
`if (redSettings.buildDir) {buildDir = redSettings.buildDir}`

**Comment by ghost** [comment]
```
case Commands.Red_Interpret:
```
and
```
case Commands.Red_Compile:
```
Both calculate the buildDir, so the whole buildDir code can be brought before the `switch`.

I might be able to do it.
But it will be after 2-3 days because I have to submit college assignment day after tomorrow, and I am yet to start 😄 
@geekyi If you would like to take over from here, I have no problem. Or I will try it on 17th, if I don't forget.

**Comment by geekyi** [comment]
If I knew how to do a pull request on a pull request, I'd do it 😛

**Comment by geekyi** [comment]
Sorry, I'd had the code and.. @qtxie I just thought, is there's any need to `cd` if you're not *build*ing i.e. compiling the .exe ? It should only change on `case Commands.Red_Compile` right?

**Comment by qtxie** [comment]
@geekyi Yes. I think you're right.

**Pull request merged**
